require_relative './test_helper'

describe 'COMMAND' do
  it 'describes all the supported commands' do
    assert_command_results [
      # Results from: echo "COMMAND INFO COMMAND DEL GET SET TTL PTTL LRANGE LPUSH LPUSHX RPUSH RPUSHX LLEN LPOP BLPOP RPOP BRPOP RPOPLPUSH BRPOPLPUSH LTRIM LSET LREM LPOS LINSERT LINDEX TYPE" | nc -c -v localhost 6379 | pbcopy
      [ 'COMMAND', "*25\r\n*7\r\n$7\r\ncommand\r\n:-1\r\n*3\r\n+random\r\n+loading\r\n+stale\r\n:0\r\n:0\r\n:0\r\n*2\r\n+@slow\r\n+@connection\r\n*7\r\n$3\r\ndel\r\n:-2\r\n*1\r\n+write\r\n:1\r\n:-1\r\n:1\r\n*3\r\n+@keyspace\r\n+@write\r\n+@slow\r\n*7\r\n$3\r\nget\r\n:2\r\n*2\r\n+readonly\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@read\r\n+@string\r\n+@fast\r\n*7\r\n$3\r\nset\r\n:-3\r\n*2\r\n+write\r\n+denyoom\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@string\r\n+@slow\r\n*7\r\n$3\r\nttl\r\n:2\r\n*3\r\n+readonly\r\n+random\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@keyspace\r\n+@read\r\n+@fast\r\n*7\r\n$4\r\npttl\r\n:2\r\n*3\r\n+readonly\r\n+random\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@keyspace\r\n+@read\r\n+@fast\r\n*7\r\n$6\r\nlrange\r\n:4\r\n*1\r\n+readonly\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@read\r\n+@list\r\n+@slow\r\n*7\r\n$5\r\nlpush\r\n:-3\r\n*3\r\n+write\r\n+denyoom\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@fast\r\n*7\r\n$6\r\nlpushx\r\n:-3\r\n*3\r\n+write\r\n+denyoom\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@fast\r\n*7\r\n$5\r\nrpush\r\n:-3\r\n*3\r\n+write\r\n+denyoom\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@fast\r\n*7\r\n$6\r\nrpushx\r\n:-3\r\n*3\r\n+write\r\n+denyoom\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@fast\r\n*7\r\n$4\r\nllen\r\n:2\r\n*2\r\n+readonly\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@read\r\n+@list\r\n+@fast\r\n*7\r\n$4\r\nlpop\r\n:2\r\n*2\r\n+write\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@fast\r\n*7\r\n$5\r\nblpop\r\n:-3\r\n*2\r\n+write\r\n+noscript\r\n:1\r\n:-2\r\n:1\r\n*4\r\n+@write\r\n+@list\r\n+@slow\r\n+@blocking\r\n*7\r\n$4\r\nrpop\r\n:2\r\n*2\r\n+write\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@fast\r\n*7\r\n$5\r\nbrpop\r\n:-3\r\n*2\r\n+write\r\n+noscript\r\n:1\r\n:-2\r\n:1\r\n*4\r\n+@write\r\n+@list\r\n+@slow\r\n+@blocking\r\n*7\r\n$9\r\nrpoplpush\r\n:3\r\n*2\r\n+write\r\n+denyoom\r\n:1\r\n:2\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@slow\r\n*7\r\n$10\r\nbrpoplpush\r\n:4\r\n*3\r\n+write\r\n+denyoom\r\n+noscript\r\n:1\r\n:2\r\n:1\r\n*4\r\n+@write\r\n+@list\r\n+@slow\r\n+@blocking\r\n*7\r\n$5\r\nltrim\r\n:4\r\n*1\r\n+write\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@slow\r\n*7\r\n$4\r\nlset\r\n:4\r\n*2\r\n+write\r\n+denyoom\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@slow\r\n*7\r\n$4\r\nlrem\r\n:4\r\n*1\r\n+write\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@slow\r\n*7\r\n$4\r\nlpos\r\n:-3\r\n*1\r\n+readonly\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@read\r\n+@list\r\n+@slow\r\n*7\r\n$7\r\nlinsert\r\n:5\r\n*2\r\n+write\r\n+denyoom\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@write\r\n+@list\r\n+@slow\r\n*7\r\n$6\r\nlindex\r\n:3\r\n*1\r\n+readonly\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@read\r\n+@list\r\n+@slow\r\n*7\r\n$4\r\ntype\r\n:2\r\n*2\r\n+readonly\r\n+fast\r\n:1\r\n:1\r\n:1\r\n*3\r\n+@keyspace\r\n+@read\r\n+@fast\r\n" ],
    ]
  end
end
